service: hub-delivery-api

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  apiName: ${self:service}-${self:custom.stage}

  stackTags:
    service: ${self:service}
    stage:   ${self:custom.stage}
    product: ${self:custom.product}

  environment:
    stage: ${self:custom.stage}
    region: ${aws:region} 
    service: ${self:service}

plugins:
  - serverless-plugin-resource-tagging
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${sls:stage}
  product: delivery

  dynamodb:
    stages:
      - dev
      - prd

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  app:
    handler: dist/index.handler
    name: hub-delivery-api-${self:custom.stage}
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hub-users-${self:custom.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: cpf
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: GsiEmail
            KeySchema:
            - AttributeName: email
              KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE
          - IndexName: GsiCpf
            KeySchema:
            - AttributeName: cpf
              KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE