service: hub-delivery-api

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: dev
  
  dynamodb:
    stages:
      - dev

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hub-users-${self:custom.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: cpf
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: cpf
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsiEmail
            KeySchema:
            - AttributeName: email
              KeyType: HASH
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE